apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  annotations:
    app.accuknox.com/source: Discovery Engine
    app.accuknox.com/type: discovered
  creationTimestamp: "2025-05-29T20:23:02Z"
  generation: 1
  name: autopol-system-1692077598
  namespace: agentic-ai
  resourceVersion: "5352865"
  uid: ab39662b-bd00-4b0d-9fae-1d89d915fd6c
spec:
  action: Allow
  file:
    matchDirectories:
    - action: Block
      dir: /root/.aws/
      recursive: true
    - dir: /
      recursive: true
    - dir: /root/.aws/
      fromSource:
      - path: /usr/bin/python3.12
      recursive: true
  network:
    matchProtocols:
    - fromSource:
      - path: /usr/bin/python3.12
      protocol: icmp
    - fromSource:
      - path: /usr/bin/python3.12
      protocol: raw
    - fromSource:
      - path: /usr/bin/python3.12
      protocol: tcp
    - fromSource:
      - path: /usr/bin/python3.12
      protocol: udp
  process:
    matchPaths:
    - execname: containerd-shim-runc-v2
    - path: /.venv/bin/python
    - path: /app/start-server.sh
    - path: /bin/busybox
    - path: /bin/sh
    - path: /sandbox/bin/sandbox_python3.12
    - path: /usr/bin/python3.12
    - path: /usr/bin/sandbox_python3.12
  selector:
    matchLabels:
      app: agentic-ai-strands
  severity: 1
