apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentic-ai-strands
  labels:
    app: agentic-ai-strands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentic-ai-strands
  template:
    metadata:
      labels:
        app: agentic-ai-strands
    spec:
      containers:
      - name: agentic-ai-strands
        image: nyrahul/agentic-ai-strands:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: agentic-ai-strands-service
spec:
  selector:
    app: agentic-ai-strands
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

